- name: Install python3
  apt:
    name:
      - python3
      - python3-virtualenv
      - rsync
    state: present # якщо пакет встановлений, не оновлювати
    update_cache: true

- name: Copy file requirements.txt
  ansible.builtin.copy:
    src: requirements.txt
    dest: /root/requirements.txt

- name: Install specified python requirements in indicated (virtualenv)
  ansible.builtin.pip:
    requirements: /root/requirements.txt
    virtualenv: /root/.venv

- name: Install build tools
  apt:
    name:
      - debootstrap
      - kpartx
      - qemu-utils
      - build-essential
      - python-pip
      - python-lzma
      - yum
      - yum-utils
      - python-yaml
    state: present # якщо пакет встановлений, не оновлювати
    update_cache: true