- name: Creates directory
  ansible.builtin.file:
    path: /root/build
    state: directory

- name: Copy file image.yaml
  ansible.builtin.copy:
    src: image.yaml
    dest: /root/build/image.yaml

- name: Run build images...
  ansible.builtin.command:
    cmd: /root/.venv/bin/diskimage-builder image.yaml
    chdir: /root/build


